### ISSUE TITLE
[Suggestion] Emotes title

### ISSUE THREAD

**Issue by madjake45** [ExuDev/BeamExtended#4]
Rather than using the default title for the img links it might be worth using the bs-tooltip and data-title as the css that is used in beam will instantly show rather than having to hover

**Comment by Exuviax** [comment]
Hmm, I actually saw this in the code and completely over looked it. However it is a great addition and I will definitely look into it!

**Comment by Exuviax** [comment]
I've been checking into this,and it doesn't seem that we can actually call to this feature yet. We are working on a way of implementing our own way for instant pop-ups
